#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

for file in $STAGED_GO_FILES; do
    ## format our file
    go fmt $file
    ## add any potential changes from our formatting to the 
    ## commit
    git add $file
done