CREATE TYPE "status" AS ENUM (
  'draft',
  'published'
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "interests" uuid[],
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "body" text NOT NULL,
  "user_id" uuid,
  "username" varchar,
  "status" status NOT NULL,
  "category" varchar NOT NULL,
  "created_at" timestamp,
  "published_at" timestamp,
  "last_modified" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "username" varchar,
  "post_id" integer,
  "body" text NOT NULL,
  "created_at" timestamp
);

COMMENT ON COLUMN "posts"."body" IS 'Content of the blog post';

COMMENT ON COLUMN "comments"."body" IS 'Content of the comment';

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "comments" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
