// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNewComment(ctx context.Context, arg CreateNewCommentParams) (Comment, error)
	CreateNewPost(ctx context.Context, arg CreateNewPostParams) (Post, error)
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) (User, error)
	CreateNewUserSession(ctx context.Context, arg CreateNewUserSessionParams) (Session, error)
	DeleteCommentByID(ctx context.Context, id uuid.UUID) error
	DeletePostByID(ctx context.Context, id uuid.UUID) error
	DeleteSessionById(ctx context.Context, id uuid.UUID) error
	DeleteUserAccount(ctx context.Context, username string) error
	GetAllPosts(ctx context.Context) ([]GetAllPostsRow, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetCommentsByPostID(ctx context.Context, postID uuid.UUID) ([]Comment, error)
	GetCommentsByUserName(ctx context.Context, username string) ([]Comment, error)
	GetPostById(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostsByCategory(ctx context.Context, category string) ([]Post, error)
	GetPostsByUserName(ctx context.Context, username string) ([]Post, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserSessionsByUsername(ctx context.Context, username string) ([]Session, error)
	UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) (Post, error)
	UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) (Post, error)
	UpdateUserInterestsByUsername(ctx context.Context, arg UpdateUserInterestsByUsernameParams) error
}

var _ Querier = (*Queries)(nil)
